USE MASTER
GO
CREATE DATABASE PROY_SISE_SEGURIDAD
GO
USE PROY_SISE_SEGURIDAD
GO
/*
- muchas tablas
juntar persona con usuario
*/
--CREATE TABLE PERSONA(
--PERSONA_ID INT,
--PERSONA_NOMBRE_1 VARCHAR(70),
--PERSONA_NOMBRE_2 VARCHAR(70),
--PERSONA_APELLIDO_1 VARCHAR(70),
--PERSONA_APELLIDO_2 VARCHAR(70),
--PERSONA_CORREO VARCHAR(300)
--)
GO
CREATE TABLE USUARIO(
USUARIO_ID INT,
PERSONA_NOMBRES VARCHAR(200),
PERSONA_APELLIDOS VARCHAR(200),
PERSONA_CORREO VARCHAR(300),
USUARIO_USER VARCHAR(20),
USUARIO_PASS VARCHAR(20),
USUARIO_DEFAULT_PASSWORD CHAR(1),
USUARIO_ESTADO CHAR(1)
)
GO
CREATE TABLE PERFIL(
PERFIL_ID INT,
PERFIL_DESCRIPCION VARCHAR(100),
PERFIL_P_RANGO_HORARIO CHAR(1),
PERFIL_P_VIGENCIA VARCHAR(10),
PERFIL_P_RANGO_DIAS CHAR(7),
PERFIL_ESTADO CHAR(1)
)
GO
CREATE TABLE APLICACION(
APLICACION_ID CHAR(6),
APLICACION_NOMBRE VARCHAR(50),
APLICACION_DESCRIPCION VARCHAR(100),
APLICACION_PATH VARCHAR(100),
APLICACION_ESTADO CHAR(1)
)
GO
CREATE TABLE APLICACION_PERFIL(
APLICACION_PERFIL_ID INT,
PERFIL_ID INT,
APLICACION_ID CHAR(6),
APLICACION_PERFIL_ESTADO CHAR(1)
)
GO
CREATE TABLE USUARIO_APLICACION_PERFIL(
USUARIO_ID INT,
APLICACION_PERFIL_ID INT,
USUARIO_APLICACION_PERFIL_ESTADO CHAR(1)
)
GO
CREATE TABLE MENU(
MENU_ID INT,
PERFIL_ID INT,
MENU_CONTENIDO VARCHAR(50),
MENU_LINK VARCHAR(100)
)
GO
CREATE TABLE SUBMENU_1(
SUBMENU_1_ID INT,
MENU_ID INT,
SUBMENU_1_CONTENIDO VARCHAR(50),
SUBMENU_1_LINK VARCHAR(100)
)
GO
CREATE TABLE SUBMENU_2(
SUBMENU_2_ID INT,
SUBMENU_1_ID INT,
SUBMENU_2_CONTENIDO VARCHAR(50),
SUBMENU_2_LINK VARCHAR(100)
)
